flags: {}
packages:
- '.'
extra-deps:
- Glob-0.7.5
- StateVar-1.1.0.4
- async-2.1.0
- attoparsec-0.13.0.2
- base-orphans-0.5.4
- bifunctors-5.2
- blaze-builder-0.4.0.2
- comonad-5
- contravariant-1.4
- distributive-0.5.0.2
- dlist-0.7.1.2
- exceptions-0.8.2.1
- free-4.12.4
- hashable-1.2.4.0
- hierarchy-0.3.1
- mmorph-1.0.6
- monad-control-1.0.1.0
- mtl-2.2.1
- network-2.6.2.1
- pipes-4.1.8
- pipes-bytestring-2.1.2
- pipes-files-0.1.1
- pipes-group-1.0.4
- pipes-parse-3.0.5
- pipes-safe-2.2.3
- pipes-text-0.0.2.1
- posix-paths-0.2.1.0
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2
- random-1.1
- regex-base-0.93.2
- regex-posix-0.95.2
- scientific-0.3.4.6
- semigroupoids-5.0.1
- semigroups-0.18.1
- stm-2.4.4.1
- streaming-commons-0.1.15.3
- tagged-0.8.3
- text-1.2.2.1
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unix-compat-0.4.1.4
- unordered-containers-0.2.7.0
- vector-0.11.0.0
- void-0.7.1
- zlib-0.6.1.1
resolver: ghc-7.10.1
